apiVersion: topo.nddr.yndd.io/v1alpha1
kind: TopologyNode
metadata:
  name: dcgw2
  namespace: default
spec:
  oda:
  - key: organization
    value: nokia
  - key: deployment
    value: region1
  topology-name: fabric1
  node:
    kind-name: sros
    tag:
    - {key: position, value: dcgw}
