apiVersion: topo.nddr.yndd.io/v1alpha1
kind: Topology
metadata:
  name: fabric1
  namespace: default
spec:
  oda:
  - key: organization
    value: nokia
  - key: deployment
    value: region1
  topology:
    kind:
    - name: srl
      tag:
      - key: platform
        value: ixrd2
    - name: sros
      tag:
      - key: platform
        value: sr1
    - name: linux
      