apiVersion: topo.nddr.yndd.io/v1alpha1
kind: TopologyLink
metadata:
  name: link49-leaf1-leaf2
  namespace: default
spec:
  oda:
  - key: organization
    value: nokia
  - key: deployment
    value: region1
  topology-name: fabric1
  link:
    tag:
    - {key: lag-member, value: "true"}
    endpoints:
    - node-name: leaf1
      interface-name: int-1/1/49
      tag:
      - {key: kind, value: infra}
      - {key: lag-name, value: lag-50}
    - node-name: leaf2
      interface-name: int-1/1/49
      tag:
      - {key: kind, value: infra}
      - {key: lag-name, value: lag-50}